### ISSUE TITLE
✨ [FEATURE] 스크랩 관련 기능 추가

### ISSUE THREAD

**Issue by chamm99** [News-Snap/News-Snap-Backend#1]
## 📝 개요
- 스크랩 관련 기능 추가

## ✔️ To-Do
- [ ] 스크랩 새로 쓰기 API
- [ ] 스크랩 이어 쓰기 API
- [ ] 내가 쓴 스크랩 목록 조회 API (날짜별, 키워드 별 조회)
- [ ] 메인 화면 Top 4 키워드 조회 및 키워드 별 스크랩 조회 API
