### ISSUE TITLE
✨ [FEATURE] 게스트 로그인 관련 기능 추가

### ISSUE THREAD

**Issue by Shin-JiHyun** [News-Snap/News-Snap-Backend#5]
## 📝 개요
- 게스트 로그인 관련 기능 추가

## ✔️ To-Do
- [ ] 게스트 계정 등록 및 로그인 (토큰 발급) 
- [ ] jwt인증(서블릿 필터)
- [ ] 비밀번호 암호화
- [ ] 분실 계정 찾기 (계정 검색)
- [ ] 회원 탈퇴
- [ ] 로그 아웃

## 🛑 게스트 로그인 수정할 사항
- [ ] @AuthenticationPrincipal 작동 확인
- [ ] 회원가입, 로그인 검증 및 작동 로직 service 클래스로 빼기
